const SUMMARIZE_SYSTEM =
  "Summarize this coding conversation in under 50 characters.\nCapture the main task, key files, problems addressed, and current status."
const HAIKU_SYSTEM =
  "Analyze this message and come up with a single positive, cheerful and delightful verb in gerund form that's related to the message. Only include the word with no other text or punctuation. The word should have the first letter capitalized. Add some whimsy and surprise to entertain the user. Ensure the word is highly relevant to the user's message. Synonyms are welcome, including obscure words. Be careful to avoid words that might look alarming or concerning to the software engineer seeing it as a status notification, such as Connecting, Disconnecting, Retrying, Lagging, Freezing, etc. NEVER use a destructive word, such as Terminating, Killing, Deleting, Destroying, Stopping, Exiting, or similar. NEVER use a word that may be derogatory, offensive, or inappropriate in a non-coding context, such as Penetrating."

const HAIKU_RESPONSES = [
  "Enchanting",
  "Delighting",
  "Sparkling",
  "Thriving",
  "Blossoming",
  "Radiating",
  "Flourishing",
  "Gleaming",
  "Beaming",
  "Charming",
  "Glittering",
  "Wondrousing",
  "Jubilating",
  "Breezing",
  "Frolicking",
  "Whizzing",
  "Zingzinging",
  "Chirping",
  "Humming",
  "Bouncing",
  "Twinkling",
  "Bubbling",
  "Soaring",
  "Dancing",
  "Skipping",
  "Melodying",
  "Dreaming",
  "Innovating",
  "Crafting",
  "Inventing",
  "Weaving",
  "Shaping",
  "Designing",
  "Composing",
  "Harmonizing",
  "Illuminating",
  "Inspiring",
  "Reveling",
  "Uplifting",
  "Gushing",
  "Buzzing",
  "Pulsating",
  "Vibrating",
  "Singing",
  "Painting",
  "Sculpting",
  "Building",
  "Creating",
  "Magnifying",
  "Enhancing",
]

export const RESPONSE_MAP = new Map<string, () => string>([
  [SUMMARIZE_SYSTEM, () => "I'm vibing no need to summarize"],
  [
    HAIKU_SYSTEM,
    () => HAIKU_RESPONSES[Math.floor(Math.random() * HAIKU_RESPONSES.length)],
  ],
])
